// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	MessageID int32            `json:"message_id"`
	RoomID    string           `json:"room_id"`
	SenderID  int32            `json:"sender_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type MessagesStatus struct {
	MessageID int32            `json:"message_id"`
	UserID    int32            `json:"user_id"`
	IsRead    bool             `json:"is_read"`
	ReadAt    pgtype.Timestamp `json:"read_at"`
}

type Room struct {
	RoomID string `json:"room_id"`
}

type Session struct {
	ID           string      `json:"id"`
	UserID       int32       `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	IsRevoked    bool        `json:"is_revoked"`
	CreatedAt    pgtype.Date `json:"created_at"`
	ExpiresAt    pgtype.Date `json:"expires_at"`
}

type User struct {
	ID          int32       `json:"id"`
	Username    string      `json:"username"`
	Email       pgtype.Text `json:"email"`
	DateOfBirth string      `json:"date_of_birth"`
	Password    string      `json:"password"`
	CreatedAt   pgtype.Date `json:"created_at"`
}
