// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountUnreadMessages(ctx context.Context, userID int32) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateMessageStatus(ctx context.Context, arg CreateMessageStatusParams) (MessagesStatus, error)
	CreateRoom(ctx context.Context, roomID string) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, messageID int32) error
	GetMessage(ctx context.Context, messageID int32) (Message, error)
	GetMessageStatus(ctx context.Context, arg GetMessageStatusParams) (MessagesStatus, error)
	GetMessageWithStatus(ctx context.Context, arg GetMessageWithStatusParams) (GetMessageWithStatusRow, error)
	GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error)
	GetUserForLogin(ctx context.Context, arg GetUserForLoginParams) (User, error)
	GetUsersById(ctx context.Context, id int32) (User, error)
	GetUsersWithLessDate(ctx context.Context, dateOfBirth string) ([]User, error)
	ListRoomMessages(ctx context.Context, arg ListRoomMessagesParams) ([]Message, error)
	ListRoomMessagesWithStatus(ctx context.Context, arg ListRoomMessagesWithStatusParams) ([]ListRoomMessagesWithStatusRow, error)
	ListUnreadMessages(ctx context.Context, userID int32) ([]Message, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (MessagesStatus, error)
}

var _ Querier = (*Queries)(nil)
