// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (room_id) values ($1)
`

func (q *Queries) CreateRoom(ctx context.Context, roomID string) error {
	_, err := q.db.Exec(ctx, createRoom, roomID)
	return err
}
