version: '3.8'



services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=chat
    ports:
      - "5433:5432"

    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    restart: unless-stopped





